import { useState, useRef, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  ChevronLeft, Send, Copy, Check, RotateCcw, Volume2, VolumeX,
  Download, Save, X, Paperclip, ChevronDown, Sparkles, Gauge,
  MessageCircle, BarChart3, FileEdit, PenTool, Image, Video,
  FileSearch, FileText, Music, CheckCircle, RefreshCw, HeartHandshake,
} from 'lucide-react';
import { useAIWorkspace } from '@/contexts/AIWorkspaceContext';
import { WIDGETS, generateAIResponse } from '@/contexts/AIWorkspaceContext';
import { getDemoImageUrl } from '@/utils/imageGen';
import { useSettings } from '@/contexts/SettingsContext';
import { trpc } from '@/providers/trpc';

const iconMap: Record<string, React.ReactNode> = {
  'message-circle': <MessageCircle size={18} />, 'bar-chart-3': <BarChart3 size={18} />,
  'file-edit': <FileEdit size={18} />, 'pen-tool': <PenTool size={18} />,
  'image': <Image size={18} />, 'video': <Video size={18} />,
  'file-search': <FileSearch size={18} />, 'file-text': <FileText size={18} />,
  'music': <Music size={18} />, 'check-circle': <CheckCircle size={18} />,
  'refresh-cw': <RefreshCw size={18} />, 'heart-handshake': <HeartHandshake size={18} />,
};

export default function AIChatScreen() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const navigate = useNavigate();
  const {
    sessions, addMessage, addAIMessage, addImageMessage, addVersion, saveSession,
    getSession, downloadChat, copyToClipboard, speakText, stopSpeaking,
    ttsSpeed, setTtsSpeed,
  } = useAIWorkspace();
  const { getPrimaryColor } = useSettings();
  const primary = getPrimaryColor();

  const session = getSession(sessionId || '');
  const widget = session ? WIDGETS.find(w => w.id === session.widgetId) : null;

  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [showSave, setShowSave] = useState(false);
  const [showOptions, setShowOptions] = useState<string | null>(null);
  const [showVersionPicker, setShowVersionPicker] = useState<string | null>(null);
  const [saveTitle, setSaveTitle] = useState('');
  const [isSpeaking, setIsSpeaking] = useState<string | null>(null);
  const [showSpeed, setShowSpeed] = useState(false);
  const [fileInput, setFileInput] = useState<File | null>(null);
  const [generatingImage, setGeneratingImage] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // tRPC mutations for real AI and image generation
  const aiChatMutation = trpc.ai.chat.useMutation();
  const imageGenMutation = trpc.image.generate.useMutation();

  // Dynamic viewport height that accounts for mobile keyboard
  useEffect(() => {
    const updateHeight = () => {
      if (containerRef.current && window.visualViewport) {
        const vv = window.visualViewport;
        containerRef.current.style.height = `${vv.height}px`;
      }
    };
    if (window.visualViewport) {
      window.visualViewport.addEventListener('resize', updateHeight);
      window.visualViewport.addEventListener('scroll', updateHeight);
      updateHeight();
    }
    return () => {
      if (window.visualViewport) {
        window.visualViewport.removeEventListener('resize', updateHeight);
        window.visualViewport.removeEventListener('scroll', updateHeight);
      }
    };
  }, []);

  // Auto-scroll to bottom on new messages
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [sessions, isTyping]);

  const handleSend = useCallback(() => {
    const text = input.trim();
    if (!text || !sessionId || !session) return;
    setInput('');
    addMessage(sessionId, 'user', text);
    setIsTyping(true);
    const widgetId = session.widgetId;

    // Try real AI via backend first, fall back to local templates
    aiChatMutation.mutate(
      { widgetId, message: text },
      {
        onSuccess: (data) => {
          if (data?.response) {
            addAIMessage(sessionId, data.response, 94, 'Generated by GPT-4o-mini');
          } else {
            // Fallback to local templates
            const { text: responseText, confidence, reasoning } = generateAIResponse(widgetId, text, session.messages.length);
            addAIMessage(sessionId, responseText, confidence, reasoning);
          }
          setIsTyping(false);
        },
        onError: () => {
          // Fallback to local templates on API error
          const { text: responseText, confidence, reasoning } = generateAIResponse(widgetId, text, session.messages.length);
          addAIMessage(sessionId, responseText, confidence, reasoning);
          setIsTyping(false);
        },
      }
    );
  }, [input, sessionId, session, addMessage, addAIMessage, aiChatMutation]);

  const handleCopy = async (text: string, msgId: string) => {
    await copyToClipboard(text);
    setCopiedId(msgId);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleRegenerate = (msgId: string) => {
    if (!sessionId || !session) return;
    const msgIdx = session.messages.findIndex(m => m.id === msgId);
    const userMsg = msgIdx > 0 ? session.messages[msgIdx - 1] : null;
    const triggerText = userMsg?.role === 'user' ? userMsg.content : '';
    const { text: newText } = generateAIResponse(session.widgetId, triggerText, msgIdx + 1);
    addVersion(sessionId, msgId, newText);
  };

  const handleGenerateImage = async () => {
    if (!sessionId || !session) return;
    // Build prompt from conversation
    const userMessages = session.messages.filter(m => m.role === 'user').map(m => m.content);
    const prompt = userMessages.join('. ').slice(0, 500) || 'Abstract artistic composition';
    setGeneratingImage(true);

    // Use server-side DALL-E proxy (no API key needed on client)
    imageGenMutation.mutate(
      { prompt },
      {
        onSuccess: (data) => {
          if (data?.imageUrl) {
            addImageMessage(sessionId, data.imageUrl, prompt);
          }
          setGeneratingImage(false);
        },
        onError: () => {
          // Fallback to placeholder on error
          const imageUrl = getDemoImageUrl(prompt);
          addImageMessage(sessionId, imageUrl, prompt);
          setGeneratingImage(false);
        },
      }
    );
  };

  const handleSpeak = (text: string, msgId: string) => {
    if (isSpeaking === msgId) {
      stopSpeaking();
      setIsSpeaking(null);
    } else {
      setIsSpeaking(msgId);
      speakText(text);
    }
  };

  const handleSave = () => {
    if (!sessionId || !saveTitle.trim()) return;
    saveSession(sessionId, saveTitle.trim());
    setShowSave(false);
    setSaveTitle('');
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setFileInput(file);
    const reader = new FileReader();
    reader.onload = (ev) => {
      const content = ev.target?.result as string;
      if (sessionId && content) {
        addMessage(sessionId, 'user', `[Uploaded: ${file.name}]\n\n${content.slice(0, 4000)}${content.length > 4000 ? '...' : ''}`);
      }
    };
    reader.readAsText(file);
  };

  if (!session || !widget) {
    return (
      <div className="min-h-screen bg-parchment dark:bg-espresso-deep flex flex-col items-center justify-center px-8">
        <Sparkles size={48} className="text-clay/30 mb-4" />
        <p className="text-body-sm text-clay">Chat not found</p>
        <button onClick={() => navigate('/ai/workspace')} className="mt-4 px-6 py-2 rounded-full text-white text-body-sm" style={{ backgroundColor: primary }}>
          Back to Workspace
        </button>
      </div>
    );
  }

  return (
    <div ref={containerRef} className="fixed inset-0 bg-parchment dark:bg-espresso-deep flex flex-col" style={{ transition: 'height 0.1s ease-out' }}>
      {/* Header */}
      <header className="shrink-0 z-40 bg-parchment/90 dark:bg-espresso-deep/90 backdrop-blur-md px-4 pt-6 pb-3">
        <div className="flex items-center gap-3">
          <button onClick={() => navigate('/ai/workspace')} className="p-2 -ml-2"><ChevronLeft size={24} className="text-charcoal dark:text-cream-soft" /></button>
          <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0" style={{ backgroundColor: `${widget.color}15` }}>
            <span style={{ color: widget.color }}>{widget && iconMap[widget.icon]}</span>
          </div>
          <div className="flex-1 min-w-0">
            <h1 className="text-body font-medium text-charcoal dark:text-cream-soft truncate">{session.title}</h1>
            <p className="text-caption text-clay">{widget.label}</p>
          </div>
          <button onClick={() => setShowSave(true)} className="p-2"><Save size={18} className="text-clay" /></button>
          <button onClick={() => { if (session) downloadChat(session, 'txt'); }} className="p-2 -mr-2"><Download size={18} className="text-clay" /></button>
        </div>
      </header>

      {/* Chat area */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto overscroll-contain px-4 py-4 space-y-5">
        {session.messages.map((msg) => (
          <div key={msg.id} className={msg.role === 'user' ? 'flex justify-end' : 'flex gap-2.5'}>
            {msg.role === 'ai' && (
              <div className="flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center self-start" style={{ backgroundColor: `${widget.color}15` }}>
                <Sparkles size={16} style={{ color: widget.color }} />
              </div>
            )}
            <div className={msg.role === 'user' ? 'max-w-[80%]' : 'flex-1 max-w-[85%]'}>
              {/* Message bubble */}
              <div className={`rounded-2xl px-4 py-3 ${
                msg.role === 'user' ? 'text-white rounded-tr-sm' : 'bg-cream-soft dark:bg-white/5 rounded-tl-sm'
              }`} style={msg.role === 'user' ? { backgroundColor: primary } : undefined}>
                <p className={`text-body leading-relaxed ${msg.role === 'user' ? 'text-white' : 'text-warm-stone dark:text-cream-soft/80'}`}>
                  {msg.content}
                </p>
                {/* Generated image */}
                {msg.imageUrl && (
                  <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.4 }}
                    className="mt-3 rounded-xl overflow-hidden">
                    <img src={msg.imageUrl} alt="Generated" className="w-full rounded-xl" style={{ maxHeight: 400, objectFit: 'cover' }} />
                  </motion.div>
                )}
                {/* Versions */}
                {msg.versions && msg.versions.length > 1 && (
                  <div className="mt-2 pt-2 border-t border-white/10">
                    <p className="text-caption text-white/50 mb-1">Version {msg.currentVersion} of {msg.versions.length}</p>
                    <div className="flex gap-1">
                      {msg.versions.map((_, vi) => (
                        <button key={vi} className={`w-2 h-2 rounded-full ${vi === (msg.currentVersion || 0) ? 'bg-white' : 'bg-white/30'}`} />
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* AI controls bar */}
              {msg.role === 'ai' && msg.id !== 'welcome' && (
                <div className="flex items-center gap-1 mt-1.5 px-1">
                  {/* Copy */}
                  <button onClick={() => handleCopy(msg.content, msg.id)}
                    className="p-1.5 rounded-lg hover:bg-clay/10 transition-colors text-clay" title="Copy">
                    {copiedId === msg.id ? <Check size={13} className="text-emerald-500" /> : <Copy size={13} />}
                  </button>
                  {/* Regenerate */}
                  <button onClick={() => handleRegenerate(msg.id)}
                    className="p-1.5 rounded-lg hover:bg-clay/10 transition-colors text-clay" title="Regenerate">
                    <RotateCcw size={13} />
                  </button>
                  {/* Generate Image - only for image_creation widget */}
                  {widget.id === 'image_creation' && (
                    <button onClick={handleGenerateImage} disabled={generatingImage}
                      className="p-1.5 rounded-lg hover:bg-clay/10 transition-colors text-clay disabled:opacity-40 flex items-center gap-1" title="Generate image">
                      {generatingImage ? (
                        <motion.div className="w-3 h-3 rounded-full border-2 border-clay/30 border-t-primary" animate={{ rotate: 360 }} transition={{ duration: 1, repeat: Infinity, ease: 'linear' }} />
                      ) : (
                        <><Image size={13} /><span className="text-caption">Generate</span></>
                      )}
                    </button>
                  )}
                  {/* Version picker */}
                  {msg.versions && msg.versions.length > 1 && (
                    <button onClick={() => setShowVersionPicker(showVersionPicker === msg.id ? null : msg.id)}
                      className="p-1.5 rounded-lg hover:bg-clay/10 transition-colors text-clay flex items-center gap-0.5" title="Versions">
                      <span className="text-caption">{msg.versions.length}</span><ChevronDown size={11} />
                    </button>
                  )}
                  {/* TTS */}
                  <button onClick={() => handleSpeak(msg.content, msg.id)}
                    className="p-1.5 rounded-lg hover:bg-clay/10 transition-colors text-clay" title="Read aloud">
                    {isSpeaking === msg.id ? <VolumeX size={13} className="text-primary" /> : <Volume2 size={13} />}
                  </button>
                  {/* More options */}
                  <button onClick={() => setShowOptions(showOptions === msg.id ? null : msg.id)}
                    className="p-1.5 rounded-lg hover:bg-clay/10 transition-colors text-clay">
                    <ChevronDown size={13} />
                  </button>

                  <AnimatePresence>
                    {showOptions === msg.id && (
                      <motion.div initial={{ opacity: 0, y: -5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -5 }}
                        className="absolute right-4 mt-8 bg-cream-soft dark:bg-espresso-deep border border-clay/20 rounded-xl shadow-float p-1 z-50 min-w-[160px]">
                        <button onClick={() => { handleCopy(msg.content, msg.id); setShowOptions(null); }}
                          className="w-full flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-parchment dark:hover:bg-white/5 text-body-sm text-charcoal dark:text-cream-soft">
                          <Copy size={14} /> Copy
                        </button>
                        <button onClick={() => { if (session) downloadChat(session, 'txt'); setShowOptions(null); }}
                          className="w-full flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-parchment dark:hover:bg-white/5 text-body-sm text-charcoal dark:text-cream-soft">
                          <Download size={14} /> Download chat
                        </button>
                        <button onClick={() => { setShowOptions(null); }}
                          className="w-full flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-parchment dark:hover:bg-white/5 text-body-sm text-charcoal dark:text-cream-soft">
                          <Gauge size={14} /> Speed
                        </button>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              )}
            </div>
          </div>
        ))}

        {/* Typing indicator */}
        <AnimatePresence>
          {isTyping && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex gap-2.5">
              <div className="w-8 h-8 rounded-full flex items-center justify-center self-start" style={{ backgroundColor: `${widget.color}15` }}>
                <Sparkles size={16} style={{ color: widget.color }} />
              </div>
              <div className="bg-cream-soft dark:bg-white/5 rounded-2xl rounded-tl-sm px-4 py-3">
                <div className="flex gap-1.5">
                  {[0, 1, 2].map(i => (
                    <motion.div key={i} className="w-2 h-2 rounded-full" style={{ backgroundColor: primary }}
                      animate={{ opacity: [0.3, 1, 0.3] }} transition={{ duration: 1.2, repeat: Infinity, delay: i * 0.2 }} />
                  ))}
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Save modal */}
      <AnimatePresence>
        {showSave && (
          <>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setShowSave(false)} className="fixed inset-0 z-50 bg-charcoal/50 backdrop-blur-sm" />
            <motion.div initial={{ y: '100%' }} animate={{ y: 0 }} exit={{ y: '100%' }} transition={{ type: 'spring', damping: 25, stiffness: 300 }}
              className="fixed bottom-0 left-0 right-0 z-50 bg-cream-soft dark:bg-espresso-deep rounded-t-2xl p-6">
              <div className="flex justify-center pt-1 pb-4"><div className="w-10 h-1 rounded-full bg-clay/40" /></div>
              <h3 className="text-display-sm text-charcoal dark:text-cream-soft mb-4">Save Chat</h3>
              <input value={saveTitle} onChange={e => setSaveTitle(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleSave()} placeholder="Chat title..." autoFocus
                className="w-full h-[48px] rounded-xl border border-clay/20 bg-white dark:bg-white/5 px-4 text-body text-charcoal dark:text-cream-soft placeholder:text-clay/50 focus:outline-none mb-4" style={{ outlineColor: primary }} />
              <button onClick={handleSave} disabled={!saveTitle.trim()}
                className="w-full h-[48px] rounded-full text-white font-medium text-body disabled:opacity-40" style={{ backgroundColor: primary }}>Save</button>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Speed modal */}
      <AnimatePresence>
        {showSpeed && (
          <>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setShowSpeed(false)} className="fixed inset-0 z-50 bg-charcoal/50 backdrop-blur-sm" />
            <motion.div initial={{ y: '100%' }} animate={{ y: 0 }} exit={{ y: '100%' }} transition={{ type: 'spring', damping: 25, stiffness: 300 }}
              className="fixed bottom-0 left-0 right-0 z-50 bg-cream-soft dark:bg-espresso-deep rounded-t-2xl p-6">
              <div className="flex justify-center pt-1 pb-4"><div className="w-10 h-1 rounded-full bg-clay/40" /></div>
              <h3 className="text-display-sm text-charcoal dark:text-cream-soft mb-4">Speech Speed</h3>
              <div className="flex gap-3">
                {[0.5, 0.75, 1, 1.25, 1.5, 2].map(s => (
                  <button key={s} onClick={() => setTtsSpeed(s)}
                    className={`flex-1 py-3 rounded-xl text-body-sm font-medium transition-colors ${ttsSpeed === s ? 'text-white' : 'bg-parchment dark:bg-white/5 text-clay'}`}
                    style={ttsSpeed === s ? { backgroundColor: primary } : undefined}>{s}x</button>
                ))}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Input bar */}
      <div className="shrink-0 sticky bottom-0 bg-parchment/90 dark:bg-espresso-deep/90 backdrop-blur-md px-4 py-3 safe-bottom">
        <div className="flex items-center gap-2 bg-white dark:bg-white/5 rounded-xl border border-clay/20 px-4 py-2">
          <label className="p-1.5 hover:bg-clay/10 rounded-lg transition-colors cursor-pointer">
            <Paperclip size={18} className="text-clay" />
            <input type="file" accept=".txt,.pdf,.doc,.docx,.md" onChange={handleFileSelect} className="hidden" />
          </label>
          <input ref={inputRef} value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleSend()}
            placeholder={fileInput ? `${fileInput.name} attached` : `Message ${widget.label}...`}
            className="flex-1 bg-transparent text-body text-charcoal dark:text-cream-soft placeholder:text-clay/50 focus:outline-none h-10" />
          {fileInput && (
            <button onClick={() => setFileInput(null)} className="p-1"><X size={14} className="text-clay" /></button>
          )}
          <motion.button whileTap={{ scale: 0.9 }} onClick={handleSend} disabled={!input.trim()}
            className="w-9 h-9 rounded-full flex items-center justify-center disabled:opacity-30" style={{ backgroundColor: primary }}>
            <Send size={14} className="text-white ml-0.5" />
          </motion.button>
        </div>
      </div>
    </div>
  );
}
